# Generated by Django 6.0.2 on 2026-03-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['level', 'title'], 'verbose_name': 'Designation', 'verbose_name_plural': 'Designations'},
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text='A unique code for identifying the department (e.g., HR, IT).', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this department is currently active.'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='The full name of the department.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text='Hierarchy level (1 being the highest or most senior).'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='title',
            field=models.CharField(help_text='The title of the designation.', max_length=100, unique=True),
        ),
    ]
