# Generated by Django 6.0.2 on 2026-03-18 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google_ads', 'Google Ads'), ('referral', 'Referral'), ('direct_call', 'Direct Call'), ('other', 'Other')], db_index=True, default='website', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=10)),
                ('expected_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_converted', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('meeting', 'Meeting'), ('proposal', 'Proposal Sent'), ('closing', 'Deal Closed'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('note', 'Note')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('activity_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
    ]
