# Generated by Django 6.0.2 on 2026-03-18 11:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('asset_code', models.CharField(db_index=True, help_text='SKU / Unique Code', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, db_index=True, default='', max_length=100, null=True)),
                ('model_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('asset_type', models.CharField(choices=[('DEVICE', 'Device'), ('COMPONENT', 'Component'), ('ACCESSORY', 'Accessory')], default='DEVICE', max_length=20)),
                ('default_purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('default_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_serialized', models.BooleanField(default=True)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('min_stock_level', models.PositiveIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inventory Log',
                'verbose_name_plural': 'Inventory Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='inventory.asset')),
            ],
            options={
                'verbose_name': 'Inventory Balance',
                'verbose_name_plural': 'Inventory Balances',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.asset')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchase')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
            },
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(db_index=True, max_length=255, unique=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('ISSUED', 'Issued'), ('DAMAGED', 'Damaged'), ('RETURNED', 'Returned')], default='IN_STOCK', max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='inventory.asset')),
            ],
            options={
                'verbose_name': 'Serial Number',
                'verbose_name_plural': 'Serial Numbers',
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned')], default='assigned', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inventory.asset')),
                ('serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.serialnumber')),
            ],
            options={
                'verbose_name': 'Asset Assignment',
                'verbose_name_plural': 'Asset Assignments',
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('reference_type', models.CharField(max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='inventory.asset')),
            ],
            options={
                'verbose_name': 'Stock Ledger',
                'verbose_name_plural': 'Stock Ledgers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_selling_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit_cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('issued_to', models.CharField(db_index=True, max_length=255)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_outs', to='inventory.asset')),
            ],
            options={
                'verbose_name': 'Stock Out',
                'verbose_name_plural': 'Stock Outs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.supplier'),
        ),
    ]
