# Generated by Django 6.0.2 on 2026-03-18 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('lunch_time_houre', models.PositiveIntegerField(default=1)),
                ('total_working_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LEAVE', 'Leave'), ('HOLIDAY', 'Holiday'), ('WEEK_OFF', 'Week Off')], default='PRESENT', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.shift')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='staff.staff')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='attendance__date_61f2e1_idx'), models.Index(fields=['staff', 'date'], name='attendance__staff_i_960a40_idx'), models.Index(fields=['status'], name='attendance__status_132c06_idx')],
                'unique_together': {('staff', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('total_present', models.PositiveIntegerField(default=0)),
                ('total_absent', models.PositiveIntegerField(default=0)),
                ('total_leave', models.PositiveIntegerField(default=0)),
                ('total_half_day', models.PositiveIntegerField(default=0)),
                ('total_overtime_minutes', models.PositiveIntegerField(default=0)),
                ('total_late_minutes', models.PositiveIntegerField(default=0)),
                ('total_working_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_attendance', to='staff.staff')),
            ],
            options={
                'indexes': [models.Index(fields=['month', 'year'], name='attendance__month_a8a5dc_idx')],
                'unique_together': {('staff', 'month', 'year')},
            },
        ),
    ]
